name: Execute Jupyter Notebooks

on: [push, pull_request]

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute Jupyter Notebooks
      run: |
        pip install nbconvert
        find . -name "*.ipynb" -exec jupyter nbconvert --to notebook --execute --inplace {} +

    - name: Save executed notebooks as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: executed-notebooks
        path: '**/*.ipynb'
